name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare node and pnpm versions
        id: versions
        run: |
          echo "nvmrc=$(cat .nvmrc)" >> $GITHUB_OUTPUT
          echo "pnpm=$(jq -r .packageManager ./package.json | cut -d@ -f2)" >> $GITHUB_OUTPUT

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ steps.versions.outputs.pnpm }}
          run_install: false # For cache

      # pnpm should be installed before the setup-node action. REF: https://github.com/actions/setup-node/issues/530
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.nvmrc }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm eslint .

      - name: Lint markdown
        run: pnpm markdownlint .

      - name: Lint glossary
        run: pnpm lint:csv

      - name: Test
        run: pnpm test
